[tool.poetry]
name = "basic-client"
version = "0.1.0"
description = ""
authors = ["Vinayak <nayakvinayak95@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
parlant-client = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
